### PR TITLE
Convert to PHP

### PR DESCRIPTION
**Pull request by ElliotGluck**

### CODE REVIEW

**Comment by mcklyde** [comment]
Converting to PHP will have no advantage whatsoever.

**Comment by ElliotGluck** [comment]
It would make it more easily deployable

**Comment by mcklyde** [comment]
Deployment is a non issue.

**Comment by ElliotGluck** [comment]
but then we could deploy to godaddy for as low as 2.99 per month!!!!
https://www.godaddy.com/hosting/web-hosting

**Comment by lucasxz** [comment]
i love godaddy

**Pull request closed without merging**
